# render.yaml
services:
  - type: web
    name: kanban-board
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-db
          property: connectionString

databases:
  - name: kanban-db
    plan: free